name: flutter_dropzone
description: A drag-and-drop Flutter plugin (Web).
version: 1.0.0
author: DJG
homepage: www.creativephotocloud.com

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  js: ^0.6.1+1
  plugin_platform_interface: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterDropzonePlugin
        fileName: src/flutter_dropzone_plugin.dart

  assets:
    - packages/flutter_dropzone/assets/flutter_dropzone.js
